#!/usr/bin/env bash
# www.jrodal.com

# Detects whether a git remote origin is https or ssh, and then changes 
# the origin to the other one.
# i.e. if the origin is https, it converts it to ssh.
# if the origin is ssh, it converts it to https

remote="$(git remote -v | awk 'NR==1{print $2}')"

if grep -q "http\?s:" <<< "$remote"; then
    echo "Converting https to ssh"
    git remote set-url origin "$(echo "$remote" | sed 's/https:\/\/github.com\//git@github.com:/g')"
else
    echo "Converting ssh to https"
    git remote set-url origin "$(echo "$remote" | sed 's/git@github.com:/https:\/\/github.com\//g')"
fi

git remote -v
