# Reference: https://github.com/i3/i3/blob/next/etc/config

config-version = 2

# In i3, all workspaces are phantom
persistent-workspaces = []

# i3 doesn't have "normalizations" feature that why we disable them here.
# But the feature is very helpful.
# Normalizations eliminate all sorts of weird tree configurations that don't make sense.
# Give normalizations a chance and enable them back.
enable-normalization-flatten-containers = true
enable-normalization-opposite-orientation-for-nested-containers = true

start-at-login = true

# Mouse follows focus when focused monitor changes
on-focused-monitor-changed = ['move-mouse monitor-lazy-center']

default-root-container-layout = 'tiles'

[mode.main.binding]
    # See: https://nikitabobko.github.io/AeroSpace/goodies#open-a-new-window-with-applescript
    cmd-enter = 'exec-and-forget open -n -a "WezTerm"'

    # i3 wraps focus by default
    cmd-h = 'focus --boundaries-action wrap-around-the-workspace left'
    cmd-j = 'focus --boundaries-action wrap-around-the-workspace down'
    cmd-k = 'focus --boundaries-action wrap-around-the-workspace up'
    cmd-l = 'focus --boundaries-action wrap-around-the-workspace right'

    cmd-shift-h = 'move left'
    cmd-shift-j = 'move down'
    cmd-shift-k = 'move up'
    cmd-shift-l = 'move right'


    cmd-shift-q = 'close'
    cmd-b = 'exec-and-forget open -a "Google Chrome"'
    cmd-shift-s = 'exec-and-forget /Applications/flameshot.app/Contents/MacOS/flameshot gui'

    cmd-shift-f = 'fullscreen'

    cmd-semicolon = 'layout tiles horizontal vertical'
    cmd-shift-space = 'layout floating tiling' # 'floating toggle' in i3

    cmd-1 = 'workspace 1'
    cmd-2 = 'workspace 2'
    cmd-3 = 'workspace 3'
    cmd-4 = 'workspace 4'
    cmd-5 = 'workspace 5'
    cmd-6 = 'workspace 6'
    cmd-7 = 'workspace 7'
    cmd-8 = 'workspace 8'
    cmd-9 = 'workspace 9'
    cmd-0 = 'workspace 10'

    cmd-shift-1 = ['move-node-to-workspace 1', 'workspace 1']
    cmd-shift-2 = ['move-node-to-workspace 2', 'workspace 2']
    cmd-shift-3 = ['move-node-to-workspace 3', 'workspace 3']
    cmd-shift-4 = ['move-node-to-workspace 4', 'workspace 4']
    cmd-shift-5 = ['move-node-to-workspace 5', 'workspace 5']
    cmd-shift-6 = ['move-node-to-workspace 6', 'workspace 6']
    cmd-shift-7 = ['move-node-to-workspace 7', 'workspace 7']
    cmd-shift-8 = ['move-node-to-workspace 8', 'workspace 8']
    cmd-shift-9 = ['move-node-to-workspace 9', 'workspace 9']
    cmd-shift-0 = ['move-node-to-workspace 10', 'workspace 10']

    cmd-shift-r = 'reload-config'

    cmd-r = 'mode resize'

[mode.resize.binding]
    h = 'resize width -50'
    j = 'resize height +50'
    k = 'resize height -50'
    l = 'resize width +50'
    enter = 'mode main'
    esc = 'mode main'

[gaps]
inner.horizontal = 14
inner.vertical = 14
outer.left = 0
outer.bottom = 0
outer.top = 0
outer.right = 0
